version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: .next
          destination: .next
      - run:
          name: Build website
          command: yarn build
      #- run:
      #    name: Tests
      #    command: yarn test

  deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - run:
        name: Install Now
        command: yarn add now
      - run:
        name: Deploy website to NextJs
        command: yarn deploy

workflows:
  version: 2
  build_dev:
    jobs:
      - build
  build_deploy_production:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
