version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build website
          command: yarn build
      #- run:
      #    name: Tests
      #    command: yarn test
      - run:
          name: Install Now
          command: npm i -g now --silent
      - run:
          name: Deploy website to NextJs
          command: now --prod -e NODE_ENV=production --token=$ZEIT_DEPLOY_KEY --no-clipboard
